---
title: "Math 6701 HW2"
author: "Patrick Gardocki"
date: "2023-09-27"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 8.2.33

$A = \begin{bmatrix} 2 & -3 & 1 \\ 1 & 1 & -1 \\ 4 & -1 & -1\end{bmatrix}; \ B= \begin{bmatrix} -12 \\ 1 \\ 10 \end{bmatrix}; \ X= \begin{bmatrix} -1 \\ 4 \\2 \end{bmatrix}+c_1\begin{bmatrix} 2 \\ 3 \\ 5 \end{bmatrix}$
$AX=B \rightarrow  \begin{bmatrix} 2 & -3 & 1 \\ 1 & 1 & -1 \\ 4 & -1 & -1\end{bmatrix}\begin{bmatrix} x_1\\ x_2 \\ x_3 \end{bmatrix} =\begin{bmatrix} -12 \\ 1 \\ 10 \end{bmatrix}$
If $c_1=0, \ AX = \begin{bmatrix} 2 & -3 & 1 \\ 1 & 1 & -1 \\ 4 & -1 & -1\end{bmatrix} \begin{bmatrix} 1 \\ 7 \\ 7\end{bmatrix} = \begin{bmatrix} -12 \\ 1 \\ 10 \end{bmatrix}$

If $X$ is solution for $AX=0$, then $X$ is a solution for any constant, $c_1$.


$A= \begin{bmatrix} 2 & -3 & 1 \\ 1 & 1 & -1 \\ 4 & -1 & -1\end{bmatrix} \xrightarrow[\text{R2-R1}]{\text{R1/2}} \begin{bmatrix} 1 & -3/2 & 1/2  \\ 0 & 5/2 & -3/2 \\ 4 & -1 & -1\end{bmatrix} \xrightarrow[\text{R1+R2*3/2}]{\text{R2*2/5}} \begin{bmatrix} 1 & 0 & -2/5  \\ 0 & 1 & -3/5 \\ 0 & -5 & -3 \end{bmatrix} \xrightarrow[]{\text{R3-5R2}} \begin{bmatrix} 1 & 0 & -2/5  \\ 0 & 1 & -3/5 \\ 0 & 0 & 0\end{bmatrix}= RREF(A)$

$Rank(A) = 2 \\$
Nullity(A) = # of Columns - Rank $\therefore \ Nullity(A)= 3-2=1$

# 8.3.5

$A =\begin{bmatrix} 1 & 1 & 1 \\ 1 & 0 & 4 \\ 1 & 4 & 1  \end{bmatrix} \xrightarrow[]{\text{-(-R1 + R2)}} \begin{bmatrix} 1 & 1 & 1 \\ 0 & 1 & -3 \\ 0 & 3 & 0  \end{bmatrix} \xrightarrow[]{\text{R3-3R2}}  \begin{bmatrix} 1 & 1 & 1 \\ 0 & 1 & -3 \\ 0 & 0 & 9  \end{bmatrix} \xrightarrow[]{\text{R3/9}}  \begin{bmatrix} 1 & 1 & 1 \\ 0 & 1 & -3 \\ 0 & 0 & 1  \end{bmatrix} \xrightarrow[\text R1-R2-R3]{\text{R2+3R3}}  \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1  \end{bmatrix}=RREF(A)$ 

Rank = number of non-zero rows in RREF = 3


$\begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1  \end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \\ x_3\end{bmatrix} = \begin{bmatrix} 0 \\ 0 \\ 0\end{bmatrix}$

The null space is a zero vector, therefore the nullity is 0.

# 8.4.24

$$
\begin{vmatrix}
1 & 1 & 1 \\
x & y & z \\
2+x & 3+y & 4+z \\
\end{vmatrix}
= 1 \cdot
\begin{vmatrix}
y & z \\
3+y & 4+z \\
\end{vmatrix}
- 1 \cdot
\begin{vmatrix}
x & z \\
2+x & 4+z \\
\end{vmatrix}
+ 1 \cdot
\begin{vmatrix}
x & y \\
2+x & 3+y \\
\end{vmatrix}
$$
$$
\begin{vmatrix}
y & z \\
3+y & 4+z \\
\end{vmatrix}
= 4y+yz - 3z-yz
$$

$$
\begin{vmatrix}
x & z \\
2+x & 4+z \\
\end{vmatrix}
= 4x+xz - 2z-xz
$$

$$
\begin{vmatrix}
x & y \\
2+x & 3+y \\
\end{vmatrix}
= 3x+xy - 2y-xy
$$


$$
\begin{vmatrix}
1 & 1 & 1 \\
x & y & z \\
2+x & 3+y & 4+z \\
\end{vmatrix}
= -x+2y-z
$$


# 8.5.26

$det(AB)=detA*detB=detB*detA=det(BA)$

# 8.6.31

If $AA=I$, A is its own inverse.
$\begin{bmatrix} 4 & -3  \\ x & 4  \end{bmatrix} \begin{bmatrix} 4 & -3  \\ x & 4  \end{bmatrix} = \begin{bmatrix} 1 & 0  \\ 0 & 1  \end{bmatrix}$
$\begin{bmatrix} 16-3x & 0  \\ 0 & 16-3x  \end{bmatrix} \rightarrow 16-3x=1 \rightarrow x=5$
Since $AA=I$, A is its own inverse.

# 8.6.36

If either A or B is singular, then $det(A) = 0 \therefore det(AB) = det(A)*det(B) = 0$ Thus AB is singular if A or B is singular

# 8.12.36

$S=PDP^T \\$


$A =\begin{bmatrix} \frac{1}{\sqrt{3}} & \frac{1}{\sqrt{2}} & \frac{1}{\sqrt{6}} \\ \frac{-1}{\sqrt{3}} & 0 & \frac{2}{\sqrt{6}} \\ \frac{1}{\sqrt{3}} & \frac{-1}{\sqrt{2}} & \frac{1}{\sqrt{6}} \end{bmatrix} \begin{bmatrix} 1 & 0 & 0 \\ 0 & 3 & 0 \\ 0 & 0 & 5 \end{bmatrix} {\begin{bmatrix} \frac{1}{\sqrt{3}} & \frac{1}{\sqrt{2}} & \frac{1}{\sqrt{6}} \\ \frac{-1}{\sqrt{3}} & 0 & \frac{2}{\sqrt{6}} \\ \frac{1}{\sqrt{3}} & \frac{-1}{\sqrt{2}} & \frac{1}{\sqrt{6}} \end{bmatrix}}^T = \begin{bmatrix} \frac{8}{3} & \frac{4}{3} & \frac{-1}{3} \\ \frac{4}{3} & \frac{11}{3} & \frac{4}{3} \\ \frac{-1}{3} & \frac{4}{3} & \frac{8}{3} \end{bmatrix}$


# 8.9.5

$A = \begin{bmatrix} 8-\lambda & 5 \\4 & -\lambda\end{bmatrix} \rightarrow \lambda^2 -8\lambda - 20 = 0 \rightarrow \lambda = -2, \ 10$
$(-2)^m=c_o-2c_1 \\10^m=c_o+10c_1$
$c_o = \frac{5(-2)^m+10^m}{6} \\ c_1 = \frac{-(-2)^m+10^m}{12}$

$A^m = c_oI+c_1A= \begin{bmatrix} \frac{(-2)^m+2^m5^{m+1}}{6} & \frac{5(-(-2)^m+10^m)}{12}\\ \frac{-(-2)^m+10^m}{3}& \frac{5(-2)^m+10^m}{6}  \end{bmatrix}$

$m=5; \ A^5= \begin{bmatrix} 83328 & 41680 \\ 33344 & 16640\end{bmatrix}$

# 8.10.16

$\begin{bmatrix} 0 & 1 & 1 \\ 1 & 1 & 1 \\ 1 & 1 & 0 \end{bmatrix} \rightarrow \begin{bmatrix} 0-\lambda & 1 & 1 \\ 1 & 1- \lambda & 1 \\ 1 & 1 & 0- \lambda \end{bmatrix}  =0; \ \lambda = -1, \ 1\pm\sqrt{2}$

Gauss-Jordan Elimination
$\lambda = -1; \ \begin{bmatrix} 1 & 1 & 1 \\ 1 & 2 & 1 \\ 1 & 1 & 1 \end{bmatrix} \rightarrow \begin{bmatrix} 1 & 1 & 1 \\ 0 & 1 & 0 \\ 0 & 0 & 0 \end{bmatrix} \therefore K_1 = \begin{bmatrix} 1 \\ 0 \\ -1 \end{bmatrix}$

$\lambda = 1+ \sqrt2; \ \begin{bmatrix} -1+ \sqrt2 & 1 & 1 \\ 1 & \sqrt2 & 1 \\ 1 & 1 & -1+ \sqrt2 \end{bmatrix} \rightarrow \begin{bmatrix} 1 & \sqrt{2} & 1 \\ 0 & 1 & \sqrt{2} \\ 0 & 0 & 0 \end{bmatrix} \therefore K_2 = \begin{bmatrix} 1 \\ -\sqrt{2} \\ 1 \end{bmatrix}$

$\lambda = 1 - \sqrt2; \ \begin{bmatrix} -1- \sqrt2 & 1 & 1 \\ 1 & -\sqrt2 & 1 \\ 1 & 1 & -1- \sqrt2 \end{bmatrix} \rightarrow \begin{bmatrix} 1 & -\sqrt{2} & 1 \\ 0 & 1 & -\sqrt{2} \\ 0 & 0 & 0 \end{bmatrix} \therefore K_3 = \begin{bmatrix} 1 \\ \sqrt{2} \\ 1 \end{bmatrix}$


Norm of $K_1$ is $\sqrt{2}$, $K_2$ and $K_3$ is $2$,

Orthogonal Matrix:
$P =\begin{bmatrix} \frac{1}{\sqrt{2}} & \frac{1}{2} & \frac{1}{2} \\ 0 & \frac{-\sqrt{2}}{\sqrt{2}} & \frac{\sqrt{2}}{\sqrt{2}} \\ \frac{-1}{\sqrt{2}} & \frac{1}{2} & \frac{1}{2} \end{bmatrix}$


# 8.10.21

## a and b

$AK_1=\begin{bmatrix} 0 & 2 & 2 \\ 2 & 0 & 2 \\ 2 & 2 & 0 \end{bmatrix} \begin{bmatrix} 1 \\-1 \\ 0 \end{bmatrix} = \begin{bmatrix} -2 \\ 2 \\ 0 \end{bmatrix} = -2\begin{bmatrix} 1 \\-1 \\ 0 \end{bmatrix}= \lambda K_1; \ \lambda_1=-2$

$AK_2=\begin{bmatrix} 0 & 2 & 2 \\ 2 & 0 & 2 \\ 2 & 2 & 0 \end{bmatrix} \begin{bmatrix} 1 \\ 0 \\ -1  \end{bmatrix} = \begin{bmatrix} -2 \\0 \\ 2 \end{bmatrix} = -2\begin{bmatrix} 1 \\0 \\ -1 \end{bmatrix}= \lambda K_2; \ \lambda_2=-2$

$AK_2=\begin{bmatrix} 0 & 2 & 2 \\ 2 & 0 & 2 \\ 2 & 2 & 0 \end{bmatrix} \begin{bmatrix} 1 \\ 1 \\ 1  \end{bmatrix} = \begin{bmatrix} 4 \\4 \\ 4 \end{bmatrix} = 4\begin{bmatrix} 1 \\4 \\ 1 \end{bmatrix}= \lambda K_2; \ \lambda_3=4$


## c

$K_1^TK_2 = 1(1)-1(0)+0(-1)= 1 \ne 0 \therefore K_1K_2$ are not orthogonal.
$K_2^TK_2 = 1(1)+0(1)-1(1)=0 \therefore orthogonal$
$K_1^TK_3 = 1(1)-1(1)+0(1)=0 \therefore orthogonal$

Gram-Schmidt Process:
$V_1=K_1 \\ V_2 = K_2 - \frac{K_2^TV_1}{V_1^TV_1}V_1 = \begin{bmatrix} 1 \\ 0 \\ -1  \end{bmatrix}-\frac{1}{2} \begin{bmatrix} 1 \\-1 \\ 0 \end{bmatrix}= \begin{bmatrix} \frac{1}{2} \\\frac{1}{2} \\ -1 \end{bmatrix}$

Orthogonal set of eigenvectors: $(V_1,V_2,K_3)$

Norms:

$||V_1|| = \sqrt{2}$
$||V_2|| = \frac{\sqrt{3}}{\sqrt{2}}$
$||K_3|| = \sqrt{3}$


$P = \begin{bmatrix} \frac{1}{\sqrt{2}} & \frac{1}{\sqrt{6}} & \frac{1}{\sqrt{3}} \\ -\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{6}} & \frac{1}{\sqrt{3}} \\ 2 & -\frac{2}{\sqrt{6}} & \frac{1}{\sqrt{3}} \end{bmatrix}$
